### ISSUE TITLE
problem with rar files

### ISSUE THREAD

**Issue by ghost** [metatoaster/explosive.fuse#1] opened 2021-05-02 05:31 UTC
trying to mount some *.rar files on Debian 10, installed via pip. When mounting a rar file, nothing happens, command is instantly returned with a cryptic message:
'No handlers could be found for logger "explosive.fuse.mapper"'
When trying foreground mode command does not return as expected, but still produces that message.

**pip list | grep unrar**
unrar          0.4

**fusermount -V**
fusermount3 version: 3.4.1

**explode -V**
explode 0.5
explosive.fuse 0.5 (/usr/local/lib/python2.7/dist-packages)
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

p.s. zip works fine

**Comment by metatoaster** [comment] 2022-08-11 08:17
I was unable to reproduce. (Unfortunately, I wasn't getting notifications for this package, so response was... late)

Without knowing information about the nature of the rar files, nor whether or not unrar was actually installed correctly, and that I don't think the Python bindings for fuse work with fuse3, there is simply not enough information for me to work with to find the problem.  Also no log output provided with running the program with the `-d` flag (most curiously, Python 2 was used, which is no longer supported).

Most unfortunate the user already deleted the account, so I supposed I will close this until someone else encounters this problem, which they can file a new issue with more details.

**Closed as completed by metatoaster** 2022-08-11 08:17 UTC
